services:
  Apivolt:
    image: drangoht/apivolt:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Apivolt_web
    ports:
      - "3000:3000"
      - "3100-3110:3100-3110"
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=Apivolt_super_secret_key_123
      - DATABASE_URL=file:./dev.db
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Persist the local SQLite DB so users/projects aren't wiped on restart
      - ./prisma/dev.db:/app/prisma/dev.db
      # Persist the generated Next.js code folders
      - ./projects:/app/projects
    restart: unless-stopped
